from fpdf import FPDF
from app.models.analysis import AnalysisHistory
import io

class ExportService:
    @staticmethod
    def generate_repo_pdf(analysis: AnalysisHistory) -> io.BytesIO:
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Arial", "B", 24)
        pdf.set_text_color(46, 164, 79) # GitHub Green
        pdf.cell(0, 20, "Repository Analysis Report", ln=True, align="C")
        
        pdf.ln(10)
        
        # Repo Info
        pdf.set_font("Arial", "B", 16)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, f"Repository: {analysis.owner}/{analysis.repo_name}", ln=True)
        pdf.set_font("Arial", "", 12)
        pdf.cell(0, 10, f"URL: {analysis.repo_url}", ln=True)
        pdf.cell(0, 10, f"Analyzed on: {analysis.created_at.strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
        
        pdf.ln(5)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(10)
        
        # Metrics
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Core Metrics", ln=True)
        
        pdf.set_font("Arial", "", 12)
        metrics = [
            ("Health Score", f"{analysis.health_score}/100"),
            ("Stars", f"{analysis.stars:,}"),
            ("Forks", f"{analysis.forks:,}"),
            ("Open Issues", f"{analysis.open_issues:,}"),
            ("Contributors", f"{analysis.contributors_count:,}"),
        ]
        
        for label, value in metrics:
            pdf.cell(50, 10, f"{label}:", border=0)
            pdf.set_font("Arial", "B", 12)
            pdf.cell(0, 10, value, border=0, ln=True)
            pdf.set_font("Arial", "", 12)
            
        pdf.ln(10)
        
        # Languages
        if analysis.languages:
            pdf.set_font("Arial", "B", 14)
            pdf.cell(0, 10, "Language Distribution", ln=True)
            pdf.set_font("Arial", "", 12)
            
            for lang, percentage in analysis.languages.items():
                pdf.cell(50, 8, f"{lang}:", border=0)
                pdf.cell(0, 8, f"{percentage}%", border=0, ln=True)
        
        pdf.ln(10)

        # Top Contributors
        if analysis.top_contributors:
            pdf.set_font("Arial", "B", 14)
            pdf.cell(0, 10, "Top Contributors (Commits)", ln=True)
            pdf.set_font("Arial", "", 12)
            
            for contributor in analysis.top_contributors:
                name = contributor.get("login", "Unknown")
                commits = contributor.get("contributions", 0)
                pdf.cell(80, 8, f"{name}", border=0)
                pdf.cell(0, 8, f"{commits} commits", border=0, ln=True)

        pdf.ln(20)
        pdf.set_font("Arial", "I", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 10, "Generated by GitHub Repository Analyzer", align="C")
        
        # Return as bytes
        pdf_bytes = pdf.output()
        return io.BytesIO(pdf_bytes)

export_service = ExportService()
